### ISSUE TITLE
side scroll issue on mobile

### ISSUE THREAD

**Issue by rimmesbe** [Rishirandhawa/colmaracademy#1]
Be careful with padding and margins with large width percentages as they can cause overflow. In this case the margin on your images in mobile display are expanding beyond the width of the body element creating a slight side scroll issue. I would remove the margin and just use width: 100%;

https://github.com/Rishirandhawa/colmaracademy/blob/master/resources/css/style.css#L261-L265

**Comment by Rishirandhawa** [comment]
Change made. Thanks for the feedback.
