### ISSUE TITLE
html looks good

### ISSUE THREAD

**Issue by rimmesbe** [Rishirandhawa/colmaracademy#3]
Your html is very organized and well structured. One thing you could do to take it to the next level is start incorporating more semantic tags. You are using some like `<header> and `<nav>` but there are many more like: `<main> <footer> <section> <article> <aside> <figure>` and many many more. Here is a good article for getting started:
https://www.pluralsight.com/guides/html-css/semantic-html?aid=701j0000001heIqAAI&promo=&oid=&utm_source=google&utm_medium=ppc&utm_campaign=CA_Dynamic&utm_content=&utm_term=&gclid=CjwKCAjwlrnNBRBMEiwApKU4PBiUM7wtxiyqNw-6Zoikh6ChlNul6tTL839Zj2h_JNTZcK6PE5WWlRoCiOYQAvD_BwE

https://github.com/Rishirandhawa/colmaracademy/blob/master/index.html

**Comment by Rishirandhawa** [comment]
Thanks. Will incorporate this more
