### ISSUE TITLE
media query break points

### ISSUE THREAD

**Issue by rimmesbe** [Rishirandhawa/colmaracademy#4]
940px is a rather larger breakpoint for mobile display, usually it will be more in the realm of 480px. But normally there is a tablet break point between the mobile and desktop so I understand the large choice.

https://github.com/Rishirandhawa/colmaracademy/blob/master/resources/css/style.css#L468

**Comment by Rishirandhawa** [comment]
Yes. Wanted to have breakpoint at the level of ipad. Although its still not covering ipad pro. Appreciate the feedback
