### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by rimmesbe** [Rishirandhawa/colmaracademy#5]
Grade: Satisfactory

Summary: Nice job on this project, the site looks good. You used many good techniques and kept your code well organized. Take a look at the issues I created for some minor tweak suggestions and some new techniques you can look into. Overall well done, hope your enjoyed the course!

**Comment by Rishirandhawa** [comment]
Thank you for the feedback. I have made all proposed changes and published the new version in repo. Thanks a lot for all the detailed feedback
